ALTER TABLE goals ADD COLUMN cover_x REAL NOT NULL DEFAULT 50;
ALTER TABLE goals ADD COLUMN cover_y REAL NOT NULL DEFAULT 50;
ALTER TABLE countries ADD COLUMN cover_x REAL NOT NULL DEFAULT 50;
ALTER TABLE countries ADD COLUMN cover_y REAL NOT NULL DEFAULT 50;
ALTER TABLE places ADD COLUMN cover_x REAL NOT NULL DEFAULT 50;
ALTER TABLE places ADD COLUMN cover_y REAL NOT NULL DEFAULT 50;
